# Generated by Django 4.0.2 on 2022-03-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='username',
        ),
    ]
